### ISSUE TITLE
[Automation] Support OSX and Windows workers locally with Vagrant

### ISSUE THREAD

**Issue by v1v** [elastic/apm-pipeline-library#225]
Similar to https://github.com/elastic/apm-pipeline-library/pull/223

## Tasks
- [x] Where those vagrant boxes are stored
- [x] Document how to use them
- [x] Confirm whether the Vagrantfile can be exposed outside.
